### ISSUE TITLE
Failed to build as standalone package

### ISSUE THREAD

**Issue by Karlson2k** [xbmc/screensaver.greynetic#19]
Looks like CMake module is missing.
CMake log:
```
...
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking to see if CXX compiler accepts flag -flto
-- Checking to see if CXX compiler accepts flag -flto - yes
-- Found OpenGl: /usr/lib64/libGL.so
CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "Findglm.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "glm", but
  CMake did not find one.

  Could not find a package configuration file provided by "glm" with any of
  the following names:

    glmConfig.cmake
    glm-config.cmake

  Add the installation prefix of "glm" to CMAKE_PREFIX_PATH or set "glm_DIR"
  to a directory containing one of the above files.  If "glm" provides a
  separate development package or SDK, be sure it has been installed.
````

**Comment by AlwinEsch** [comment]
Need a bit more information to know why.

- Is on Linux or other "Filesystem Hierarchy Standard" based OS?
- Which Linux Distrubition?
- How you try to create?

WIth a simple `cmake ..` they not work if related depends not installed in system, e.g. Ubuntu/Debian need there then a `sudo apt install libglm-dev`, see this  [`debian/control`](https://github.com/xbmc/screensaver.greynetic/blob/Matrix/debian/control#L4-L6) file and `Build-Depends` there.

To build more distribution independent is Kodi's build system used e.g. with:
```
mkdir build && cd build && cmake -DADDONS_TO_BUILD=$(basename $(dirname $(pwd))) -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/.kodi/addons -DPACKAGE_ZIP=1  ../../xbmc/cmake/addons && make
```
Like this I use for builds, the `../../xbmc/cmake/addons` need then maybe a bit changed to match Kodi's source folder.

**Comment by AlwinEsch** [comment]
About the GLM:
- Which OS you use?
- What Version of GLM is installed?

Seen on Ubuntu they added a new GLM version and where install becomes done with a debian copy only (GLM has removed install, for me not understandable reason), maybe with them was come the error and a `Findglm.cmake` is needed.

**Comment by Karlson2k** [comment]
The problem was with glm package on Gentoo.
As upstream changed install system (actually, not install at all), cmake module was not included in gentoo package.

**Comment by AlwinEsch** [comment]
Fixed with https://github.com/xbmc/screensaver.greynetic/pull/23 (Leia) and https://github.com/xbmc/screensaver.greynetic/pull/22 (Matrix).

Also are new versions released about.
